---
- name: Ensure Java installation directory exists
  ansible.builtin.file:
    path: "{{ java_install_dir }}"
    state: directory
    mode: '0755'

- name: Download Oracle Java
  ansible.builtin.get_url:
    url: "{{ java_url }}"
    dest: "/tmp/jdk-{{ java_version }}_linux-x64_bin.tar.gz"

- name: Extract Oracle Java
  ansible.builtin.unarchive:
    src: "/tmp/jdk-{{ java_version }}_linux-x64_bin.tar.gz"
    dest: "{{ java_install_dir }}"
    remote_src: true

- name: Find the extracted JDK directory
  find:
    paths: "{{ java_install_dir }}"
    file_type: directory
    use_regex: true
    patterns: 'jdk-21.*'
  register: found_jdk_directory

- name: Create Java Dir
  ansible.builtin.file: 
    path: /usr/bin/java/jdk-{{java_version}}
    state: directory 
    owner: root 
    group: root
    mode: '0755'

- name: Rename extracted folder
  command: mv {{ item.path }} /usr/bin/java/jdk-{{java_version}}
  loop: "{{ found_jdk_directory.files }}"
  when: found_jdk_directory.matched > 0

- name: Update alternatives for java
  community.general.alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/jdk-{{java_version}}/bin/java
    priority: 1

- name: Update alternatives for javac
  community.general.alternatives:
    name: javac
    link: /usr/bin/javac
    path: /usr/lib/jvm/jdk-{{java_version}}/bin/javac
    priority: 1

- name: Set Oracle Java as the default
  ansible.builtin.command: update-alternatives --set java {{ java_insta_dir.dest}}/bin/java

- name: Set Oracle Javac as the default
  ansible.builtin.command: update-alternatives --set javac {{ java_insta_dir.dest }}/bin/javac

- name: Set JAVA_HOME environment variable
  ansible.builtin.lineinfile:
    path: /etc/profile.d/java.sh
    state: present
    create: true
    line: "export JAVA_HOME={{ java_insta_dir.dest }}"
    mode: '0755'

- name: Load the JAVA_HOME environment variable
  ansible.builtin.shell: source /etc/profile.d/java.sh
  args:
    executable: /bin/bash

- name: Verify Java installation
  ansible.builtin.command: java -version
  register: java_version_output

- name: Print Java version
  ansible.builtin.debug:
    msg: "{{ java_version_output.stdout }}"
